import React, { useState, useRef } from 'react';
import { Download, Check, Loader2 } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import { generateAndDownloadPdf, PDF_STYLES } from '../../utils/downloadPdf';

interface DownloadButtonProps {
    content: string;
    title: string;
}

const DownloadButton: React.FC<DownloadButtonProps> = ({ content, title }) => {
    const [isDownloading, setIsDownloading] = useState(false);
    const [downloadDone, setDownloadDone] = useState(false);
    const hiddenRef = useRef<HTMLDivElement>(null);

    const handleDownload = async () => {
        if (!hiddenRef.current || isDownloading) return;
        setIsDownloading(true);
        setDownloadDone(false);

        try {
            await generateAndDownloadPdf({
                content,
                title,
                containerElement: hiddenRef.current,
            });

            setDownloadDone(true);
            setTimeout(() => setDownloadDone(false), 2500);
        } catch (err) {
            console.error('[DownloadButton] Error:', err);
        } finally {
            setIsDownloading(false);
        }
    };

    return (
        <div className="relative inline-flex">
            {/* Download Button */}
            <button
                onClick={handleDownload}
                disabled={isDownloading}
                className="relative w-8 h-8 flex items-center justify-center text-gray-400 hover:text-gray-900 dark:hover:text-white hover:bg-gray-100 dark:hover:bg-white/5 rounded-full transition-all disabled:opacity-60 overflow-hidden group/download"
                title="Download PDF"
            >
                <div className={`transition-all duration-300 ${isDownloading || downloadDone ? 'scale-0 opacity-0' : 'scale-100 opacity-100'}`}>
                    <Download size={16} strokeWidth={2} className="group-hover/download:text-[var(--accent-color)]" />
                </div>
                <div className={`transition-all duration-300 absolute inset-0 flex items-center justify-center ${isDownloading || downloadDone ? 'scale-110 opacity-100' : 'scale-0 opacity-0'}`}>
                    {isDownloading ? (
                        <div className="dl-loader">
                            {[...Array(12)].map((_, i) => <span key={i} />)}
                        </div>
                    ) : (
                        <Check size={16} className="text-[var(--accent-color)]" strokeWidth={3} />
                    )}
                </div>
            </button>

            {/* ─── Hidden container for PDF rendering ─── */}
            <div ref={hiddenRef} className="pdf-export-container" style={{ display: 'none' }}>
                {/* Header — no logo, clean text only */}
                <div className="pdf-header">
                    <div className="pdf-header-text">
                        <h2 style={{ margin: 0, fontWeight: 800, fontSize: '26px', color: '#000' }}>X-GPT</h2>
                        <p style={{ margin: '2px 0 0 0', fontSize: '11px', color: '#555', letterSpacing: '1.5px', textTransform: 'uppercase' as const }}>AI Generated Report</p>
                    </div>
                </div>

                {/* Content — ReactMarkdown renders the AI response */}
                <div className="pdf-content">
                    <ReactMarkdown>{content}</ReactMarkdown>
                </div>

                {/* Footer */}
                <div className="pdf-footer">
                    Generated by X-GPT &bull; {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}
                </div>
            </div>

            {/* ─── Scoped styles ─── */}
            <style>{`
                /* ─── PDF Export Styles ─── */
                ${PDF_STYLES}
                
                .dl-loader {
                    width: 18px;
                    height: 18px;
                    border: 2px solid rgba(0, 0, 0, 0.1);
                    border-top: 2px solid var(--accent-color);
                    border-radius: 50%;
                    animation: premium-spin 0.6s cubic-bezier(0.5, 0.1, 0.4, 0.9) infinite;
                }
                @keyframes premium-spin {
                    0% { transform: rotate(0deg); }
                    100% { transform: rotate(360deg); }
                }
            `}</style>
        </div>
    );
};

export default DownloadButton;
