
export type Language = 'en' | 'bn' | 'es' | 'fr' | 'de' | 'hi' | 'ja' | 'zh' | 'ru' | 'pt' | 'ar' | 'it' | 'ko' | 'tr' | 'vi' | 'nl' | 'th';

const baseTranslations = {
    settings: { en: "Settings", bn: "সেটিংস", es: "Ajustes", fr: "Paramètres", de: "Einstellungen", hi: "सेटिंग्स", ja: "設定", zh: "设置", ru: "Настройки", pt: "Configurações", ar: "الإعدادات", it: "Impostazioni", ko: "설정", tr: "Ayarlar", vi: "Cài đặt", nl: "Instellingen", th: "การตั้งค่า" },
    general: { en: "General", bn: "সাধারণ", es: "General", fr: "Général", de: "Allgemein", hi: "सामान्य", ja: "一般", zh: "常规", ru: "Общие", pt: "Geral", ar: "عام", it: "Generale", ko: "일반", tr: "Genel", vi: "Chung", nl: "Algemeen", th: "ทั่วไป" },
    notifications: { en: "Notifications", bn: "বিজ্ঞপ্তি", es: "Notificaciones", fr: "Notifications", de: "Benachrichtigungen", hi: "सूचनाएं", ja: "通知", zh: "通知", ru: "Уведомления", pt: "Notificações", ar: "الإشعارات", it: "Notifiche", ko: "알림", tr: "Bildirimler", vi: "Thông báo", nl: "Meldingen", th: "การแจ้งเตือน" },
    personalization: { en: "Personalization", bn: "ব্যক্তিগতকরণ", es: "Personalización", fr: "Personnalisation", de: "Personalisierung", hi: "निजीकरण", ja: "パーソナライズ", zh: "个性化", ru: "Персонализация", pt: "Personalização", ar: "تخصيص", it: "Personalizzazione", ko: "개인화", tr: "Kişiselleştirme", vi: "Cá nhân hóa", nl: "Personalisatie", th: "การปรับแต่ง" },
    apps: { en: "Apps", bn: "অ্যাপস", es: "Aplicaciones", fr: "Applications", de: "Apps", hi: "ऐप्स", ja: "アプリ", zh: "应用", ru: "Приложения", pt: "Apps", ar: "التطبيقات", it: "App", ko: "앱", tr: "Uygulamalar", vi: "Ứng dụng", nl: "Apps", th: "แอป" },
    dataControls: { en: "Data controls", bn: "ডেটা কন্ট্রোল", es: "Control de datos", fr: "Contrôle des données", de: "Datenkontrolle", hi: "डेटा नियंत्रण", ja: "データ管理", zh: "数据控制", ru: "Управление данными", pt: "Controle de dados", ar: "التحكم في البيانات", it: "Controllo dati", ko: "데이터 관리", tr: "Veri kontrolleri", vi: "Kiểm soát dữ liệu", nl: "Gegevensbeheer", th: "การควบคุมข้อมูล" },
    appearance: { en: "Appearance", bn: "চেহারা", es: "Apariencia", fr: "Apparence", de: "Erscheinungsbild", hi: "दिखावट", ja: "外観", zh: "外观", ru: "Внешний вид", pt: "Aparência", ar: "المظهر", it: "Aspetto", ko: "테마", tr: "Görünüm", vi: "Giao diện", nl: "Uiterlijk", th: "ลักษณะปรากฏ" },
    light: { en: "Light", bn: "আলোকিত", es: "Claro", fr: "Clair", de: "Hell", hi: "हल्का", ja: "ライト", zh: "浅色", ru: "Светлая", pt: "Claro", ar: "فاتح", it: "Chiaro", ko: "라이트", tr: "Açık", vi: "Sáng", nl: "Licht", th: "สว่าง" },
    dark: { en: "Dark", bn: "অন্ধকার", es: "Oscuro", fr: "Sombre", de: "Dunkel", hi: "गहरा", ja: "ダーク", zh: "深色", ru: "Темная", pt: "Escuro", ar: "داكن", it: "Scuro", ko: "다크", tr: "Koyu", vi: "Tối", nl: "Donker", th: "มืด" },
    custom: { en: "Custom", bn: "কাস্টম", es: "Personalizado", fr: "Personnalisé", de: "Benutzerdefiniert", hi: "कस्टम", ja: "カスタム", zh: "自定义", ru: "Свой", pt: "Personalizado", ar: "مخصص", it: "Personalizzato", ko: "커스텀", tr: "Özel", vi: "Tùy chỉnh", nl: "Aangepast", th: "กำหนดเอง" },
    accentColor: { en: "Accent color", bn: "অ্যাকসেন্ট রঙ", es: "Color de acento", fr: "Couleur d'accentuation", de: "Akzentfarbe", hi: "एक्सेन्ट रंग", ja: "アクセントカラー", zh: "强调色", ru: "Акцентный цвет", pt: "Cor de destaque", ar: "لون التمييز", it: "Colore accento", ko: "강조 색상", tr: "Vurgu rengi", vi: "Màu chủ đạo", nl: "Accentkleur", th: "สีเน้น" },
    language: { en: "Language", bn: "ভাষা", es: "Idioma", fr: "Langue", de: "Sprache", hi: "भाषा", ja: "言語", zh: "语言", ru: "Язык", pt: "Idioma", ar: "اللغة", it: "Lingua", ko: "언어", tr: "Dil", vi: "Ngôn ngữ", nl: "Taal", th: "ภาษา" },
    play: { en: "Play", bn: "প্লে", es: "Play", fr: "Jouer", de: "Abspielen", hi: "प्ले", ja: "再生", zh: "播放", ru: "Играть", pt: "Tocar", ar: "تشغيل", it: "Riproduci", ko: "재생", tr: "Oynat", vi: "Phát", nl: "Afspelen", th: "เล่น" },
    stop: { en: "Stop", bn: "স্টপ", es: "Stop", fr: "Arrêter", de: "Stopp", hi: "स्टॉप", ja: "停止", zh: "停止", ru: "Стоп", pt: "Parar", ar: "إيقاف", it: "Ferma", ko: "중지", tr: "Durdur", vi: "Dừng", nl: "Stop", th: "หยุด" },
    blue: { en: "Blue", bn: "নীল", es: "Azul", fr: "Bleu", de: "Blau", hi: "नीला", ja: "青", zh: "蓝色", ru: "Синий", pt: "Azul", ar: "أزرق", it: "Blu", ko: "파랑", tr: "Mavi", vi: "Xanh dương", nl: "Blauw", th: "ฟ้า" },
    green: { en: "Green", bn: "সবুজ", es: "Verde", fr: "Vert", de: "Grün", hi: "हरा", ja: "緑", zh: "绿色", ru: "Зеленый", pt: "Verde", ar: "أخضر", it: "Verde", ko: "초록", tr: "Yeşil", vi: "Xanh lá", nl: "Groen", th: "เขียว" },
    yellow: { en: "Yellow", bn: "হলুদ", es: "Amarillo", fr: "Jaune", de: "Gelb", hi: "पीला", ja: "黄色", zh: "黄色", ru: "Желтый", pt: "Amarelo", ar: "أصفر", it: "Giallo", ko: "노랑", tr: "Sarı", vi: "Vàng", nl: "Geel", th: "เหลือง" },
    pink: { en: "Pink", bn: "গোলাপী", es: "Rosa", fr: "Rose", de: "Rosa", hi: "गुलाबी", ja: "ピンク", zh: "粉色", ru: "Розовый", pt: "Rosa", ar: "وردي", it: "Rosa", ko: "분홍", tr: "Pembe", vi: "Hồng", nl: "Roze", th: "ชมพู" },
    orange: { en: "Orange", bn: "কমলা", es: "Naranja", fr: "Orange", de: "Orange", hi: "नारंगी", ja: "オレンジ", zh: "橙色", ru: "Оранжевый", pt: "Laranja", ar: "برتقالي", it: "Arancione", ko: "주황", tr: "Turuncu", vi: "Cam", nl: "Oranje", th: "ส้ม" },
    white: { en: "White", bn: "সাদা", es: "Blanco", fr: "Blanc", de: "Weiß", hi: "सफेদ", ja: "白", zh: "白色", ru: "Белый", pt: "Branco", ar: "أبيض", it: "Bianco", ko: "흰색", tr: "Beyaz", vi: "Trắng", nl: "Wit", th: "ขาว" },
    askAnything: { en: "Ask anything", bn: "যেকোনো কিছু জিজ্ঞাসা করুন", es: "Pregunta lo que sea", fr: "Demandez n'importe quoi", de: "Fragen Sie etwas", hi: "कुछ भी पूछें", ja: "何でも聞いてください", zh: "问任何问题", ru: "Спрашивайте о чем угодно", pt: "Pergunte qualquer coisa", ar: "اسأل أي شيء", it: "Chiedi qualsiasi cosa", ko: "무엇이든 물어보세요", tr: "Bir şey sor", vi: "Hỏi bất cứ điều gì", nl: "Vraag maar raak", th: "ถามได้ทุกอย่าง" },
    welcome: { en: "Welcome to my X-community", bn: "আমার এক্স-কমিউনিটিতে স্বাগতম", es: "Bienvenido a mi X-community", fr: "Bienvenue dans ma communauté X", de: "Willkommen in meiner X-Community", hi: "मेरी एक्स-कम्युनिटी में आपका स्वागत है", ja: "私のXコミュニティへようこそ", zh: "欢迎来到我的X社区", ru: "Добро пожаловать в мое X-сообщество", pt: "Bem-vindo à minha comunidade X", ar: "مرحباً بكم في مجتمع X الخاص بي", it: "Benvenuti nella mia comunità X", ko: "X 커뮤니티에 오신 것을 환영합니다", tr: "X topluluğuma hoş geldiniz", vi: "Chào mừng bạn đến với cộng đồng X của tôi", nl: "Welkom bij mijn X-community", th: "ยินดีต้อนรับสู่ชุมชน X ของฉัน" },
    newChat: { en: "New Chat", bn: "নতুন চ্যাট", es: "Nuevo Chat", fr: "Nouveau Chat", de: "Neuer Chat", hi: "नया चैट", ja: "新規チャット", zh: "新聊天", ru: "Новый чат", pt: "Novo Chat", ar: "دردشة جديدة", it: "Nuova Chat", ko: "새 채팅", tr: "Yeni Sohbet", vi: "Trò chuyện mới", nl: "Nieuwe chat", th: "แชทใหม่" },
    clearHistory: { en: "Clear History", bn: "ইতিহাস মুছুন", es: "Borrar historial", fr: "Effacer l'historique", de: "Verlauf löschen", hi: "इतिहास साफ़ करें", ja: "履歴をクリア", zh: "清除历史", ru: "Очистить историю", pt: "Limpar histórico", ar: "مسح سجل الدردشة", it: "Cancella cronologia", ko: "기록 삭제", tr: "Geçmişi temizle", vi: "Xóa lịch sử", nl: "Geschiedenis wissen", th: "ล้างประวัติ" },
    logout: { en: "Logout", bn: "লগআউট", es: "Cerrar sesión", fr: "Déconnexion", de: "Abmelden", hi: "लॉगआउट", ja: "ログアウト", zh: "退出", ru: "Выход", pt: "Sair", ar: "تسجيل الخروج", it: "Esci", ko: "로그아웃", tr: "Çıkış yap", vi: "Đăng xuất", nl: "Uitloggen", th: "ออกจากระบบ" },
    submit: { en: "Send", bn: "পাঠান", es: "Enviar", fr: "Envoyer", de: "Senden", hi: "भेजें", ja: "送信", zh: "发送", ru: "Отправить", pt: "Enviar", ar: "إرسال", it: "Invia", ko: "보내기", tr: "Gönder", vi: "Gửi", nl: "Verzenden", th: "ส่ง" },
    share: { en: "Share", bn: "শেয়ার", es: "Compartir", fr: "Partager", de: "Teilen", hi: "साझा करें", ja: "共有", zh: "分享", ru: "Поделиться", pt: "Compartilhar", ar: "مشاركة", it: "Condividi", ko: "공유", tr: "Paylaş", vi: "Chia sẻ", nl: "Delen", th: "แชร์" },
    copy: { en: "Copy", bn: "কপি", es: "Copiar", fr: "Copier", de: "Kopieren", hi: "कॉपी", ja: "コピー", zh: "复制", ru: "Копировать", pt: "Copiar", ar: "نسخ", it: "Copia", ko: "복사", tr: "Kopyala", vi: "Sao chép", nl: "Kopiëren", th: "คัดลอก" },
    copied: { en: "Copied!", bn: "কপি হয়েছে!", es: "¡Copiado!", fr: "Copié !", de: "Kopiert!", hi: "कॉपी किया गया!", ja: "コピーしました！", zh: "已复制！", ru: "Скопировано!", pt: "Copiado!", ar: "تم النسخ!", it: "Copiato!", ko: "복사됨!", tr: "Kopyalandı!", vi: "Đã sao chép!", nl: "Gekopieerd!", th: "คัดลอกแล้ว!" },
    cancel: { en: "Cancel", bn: "বাতিল", es: "Cancelar", fr: "Annuler", de: "Abbrechen", hi: "रद्द करें", ja: "キャンセル", zh: "取消", ru: "Отмена", pt: "Cancelar", ar: "إلغاء", it: "Annulla", ko: "취소", tr: "İptal", vi: "Hủy", nl: "Annuleren", th: "ยกเลิก" },
    delete: { en: "Delete", bn: "মুছে ফেলুন", es: "Eliminar", fr: "Supprimer", de: "Löschen", hi: "मिटाएं", ja: "削除", zh: "删除", ru: "Удалить", pt: "Excluir", ar: "حذف", it: "Elimina", ko: "삭제", tr: "Sil", vi: "Xóa", nl: "Verwijderen", th: "ลบ" },
    edit: { en: "Edit", bn: "সম্পাদনা", es: "Editar", fr: "Modifier", de: "Bearbeiten", hi: "संपादित करें", ja: "編集", zh: "编辑", ru: "Изменить", pt: "Editar", ar: "تعديل", it: "Modifica", ko: "편집", tr: "Düzenle", vi: "Chỉnh sửa", nl: "Bewerken", th: "แก้ไข" },
    download: { en: "Download", bn: "ডাউনলোড", es: "Descargar", fr: "Télécharger", de: "Herunterladen", hi: "डाउनलोड", ja: "ダウンロード", zh: "下载", ru: "Скачать", pt: "Baixar", ar: "تحميل", it: "Scarica", ko: "다운로드", tr: "İndir", vi: "Tải xuống", nl: "Downloaden", th: "ดาวน์โหลด" },
    searchChats: { en: "Search chats", bn: "চ্যাট খুঁজুন", es: "Buscar chats", fr: "Rechercher", de: "Suche", hi: "चैट खोजें", ja: "検索", zh: "搜索", ru: "Поиск", pt: "Buscar", ar: "بحث", it: "Cerca", ko: "검색", tr: "Ara", vi: "Tìm kiếm", nl: "Zoeken", th: "ค้นหา" },
};

export const translations: any = {};

const languages: Language[] = ['en', 'bn', 'es', 'fr', 'de', 'hi', 'ja', 'zh', 'ru', 'pt', 'ar', 'it', 'ko', 'tr', 'vi', 'nl', 'th'];

languages.forEach(lang => {
    translations[lang] = {};
    Object.keys(baseTranslations).forEach(key => {
        translations[lang][key] = (baseTranslations as any)[key][lang];
    });
});
